version: "3"

networks: 
  app-network:
    driver: bridge

services:  
  app:
    build: ./phpdocker/php-fpm
    container_name: app
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 40s chmod -x ./entrypoint.sh ./entrypoint.sh
    restart: always
    tty: true
    volumes:
      - ./application:/var/www
    networks: 
      - app-network
    depends_on: 
      - db
      - redis

  nginx:
    build: ./phpdocker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "8080:80"
    volumes: 
      - ./application:/var/www
    networks:
      - app-network
    depends_on: 
      - app
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "33600:3306"
    volumes: 
      - ./phpdocker/dbdata:/var/lib/mysql
      - ./phpdocker/dbschema:/application
    environment: 
      - MYSQL_DATABASE=zend3_estudo
      - MYSQL_ROOT_PASSWORD=rm8:28
      - MYSQL_USER=root
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    expose: 
      - 6379
    networks:
      - app-network

  phpmyadmin:
    build: ./phpdocker/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rm8:28
      - MYSQL_ROOT_PASSWORD=rm8:28
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network
