<h1>Post</h1>
<p>
    <a href="<?= $this->url('post', ['action' => 'save']); ?>">
        New Post
    </a>
</p>
<table>
    <thead>
        <th>Title</th>
        <th>Ações</th>
    </thead>
    <tbody>
        <?php foreach ($this->posts as $post) : ?>
            <tr>
                <td><?= $post->title; ?></td>
                <td>
                    <a href="<?= $this->url('post', ['action' => 'save', 'id' => $post->id]); ?>">Edit</a>
                    <a href="<?= $this->url('post', ['action' => 'delete', 'id' => $post->id]); ?>">Del</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>